version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - unused
  settings:
    depguard:
      rules:
        logger:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
