// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm_gen_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMultiFieldPrimaryKeyDemo = "multi_field_primary_key_demo"

// MultiFieldPrimaryKeyDemo mapped from table <multi_field_primary_key_demo>
type MultiFieldPrimaryKeyDemo struct {
	PrimaryKey1 string         `gorm:"column:primary_key_1;type:character varying(64);primaryKey" json:"primaryKey1"`
	PrimaryKey2 string         `gorm:"column:primary_key_2;type:character varying(64);primaryKey" json:"primaryKey2"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null" json:"createdAt"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null" json:"updatedAt"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deletedAt"`
}

// TableName MultiFieldPrimaryKeyDemo's table name
func (*MultiFieldPrimaryKeyDemo) TableName() string {
	return TableNameMultiFieldPrimaryKeyDemo
}
