package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestMissingExportedCommentsReportsProductionAPI(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "api/api.go", `package api

type MissingType struct{}

func MissingFunc() {}

const MissingConst = 1

var MissingVar = 2
`)

	missing, err := missingExportedComments(root)
	if err != nil {
		t.Fatalf("missing comments: %v", err)
	}

	for _, want := range []string{
		"exported type MissingType",
		"exported func MissingFunc",
		"exported const MissingConst",
		"exported var MissingVar",
	} {
		if !containsSubstring(missing, want) {
			t.Fatalf("expected %q in missing comments: %#v", want, missing)
		}
	}
}

func TestMissingExportedCommentsAcceptsDocumentedProductionAPI(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "api/api.go", `package api

// DocumentedType has a doc comment.
type DocumentedType struct{}

// DocumentedFunc has a doc comment.
func DocumentedFunc() {}

// DocumentedConst has a doc comment.
const DocumentedConst = 1

// DocumentedVar has a doc comment.
var DocumentedVar = 2
`)

	missing, err := missingExportedComments(root)
	if err != nil {
		t.Fatalf("missing comments: %v", err)
	}
	if len(missing) != 0 {
		t.Fatalf("expected no missing comments, got %#v", missing)
	}
}

func TestMissingExportedCommentsSkipsGeneratedAndTestFiles(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "api/generated.go", `// Code generated by test. DO NOT EDIT.
package api

type GeneratedType struct{}
`)
	writeTestFile(t, root, "api/api_test.go", `package api

type TestFixture struct{}

func (TestFixture) SchemaName(string) string { return "" }

func TestHelper() {}
`)
	writeTestFile(t, root, filepath.Join("orm", "example", "gorm", "postgres", "gorm_gen_repo", "repo.go"), `package repo

type GeneratedExampleType struct{}
`)

	missing, err := missingExportedComments(root)
	if err != nil {
		t.Fatalf("missing comments: %v", err)
	}
	if len(missing) != 0 {
		t.Fatalf("expected generated and test files to be skipped, got %#v", missing)
	}
}

func TestMissingExportedCommentsReturnsParseErrors(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "api/broken.go", `package api

func Broken(
`)

	if _, err := missingExportedComments(root); err == nil {
		t.Fatal("expected parse error")
	}
}

func TestIsCheckedGoFile(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{path: "api.go", want: true},
		{path: "api_test.go", want: false},
		{path: "api.gen.go", want: false},
		{path: "api.pb.go", want: false},
		{path: "README.md", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			if got := isCheckedGoFile(tt.path); got != tt.want {
				t.Fatalf("isCheckedGoFile(%q)=%v want %v", tt.path, got, tt.want)
			}
		})
	}
}

func writeTestFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir test file dir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write test file: %v", err)
	}
}

func containsSubstring(values []string, substr string) bool {
	for _, value := range values {
		if strings.Contains(value, substr) {
			return true
		}
	}
	return false
}
